import = [
  "~/.config/catppuccin/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "source ~/.zshrc; cd ~/Downloads; ftmux",
]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_title = true

#opacity = 0.8
#blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
# normal.family = "Hack Nerd Font"
size = 15

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
  { key = "Home", chars = "\u0001" },
  # { key = "Home", chars = "\u001b[H", mode = "~AppCursor" },
  { key = "End", chars = "\u0005" },
  # { key = "End", chars = "\u001b[F", mode = "~AppCursor" },
  # { key = "PageUp", chars = "\u001b[5~" },


  # NOTE: tmux
  # NOTE: prefix key is C-b "$HOME/.config/tmux/tmux.conf"
  #
  # https://www.danielcorin.com/til/alacritty/rebuilding-my-iterm-setup-in-alacritty/
  # ⌘ + enter puts window in macOS full screen
  { key = "Enter", mods = "Command", action = "ToggleFullscreen"},
  # opt + right and left jump between words
  # NOTE "$HOME/.config/zsh/bindings.sh"
  # ⌘ + d adds a pane to the right (splits window vertically)
  { key = "D",  mods = "Command", chars = "\u0002%" },
  # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
  { key = "D",  mods = "Command|Shift", chars = "\u0002\"" },
  # ⌘ + w prompts you to close the pane, "y" to confirm
  { key = "W",  mods = "Command", chars = "\u0002x" },
  { key = "T", mods = "Command", chars = "\u0002\u0063" },
  # ⌘ + arrows are for directional navigation around the panes
  { key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
  { key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
  { key = "Left", mods = "Command", chars = "\u0002\u001b[D" },
  { key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
  # ⌘ + ^ + arrows are for directional resizing of the panes
  { key = "Down", mods = "Command|Shift", chars = "\u0002\u001b[1;5B" },
  { key = "Up", mods = "Command|Shift", chars = "\u0002\u001b[1;5A" },
  { key = "Left", mods = "Command|Shift", chars = "\u0002\u001b[1;5D" },
  { key = "Right", mods = "Command|Shift", chars = "\u0002\u001b[1;5C" },
  # ⌘ + ⇧ + enter for zoom pane
  { key = "Enter", mods = "Command|Shift", chars = "\u0002\u007a" },
  # ⌃ + Tab + Shift for navigate to next and previous window
  { key = "Tab", mods = "Control|Shift", chars = "\u0002\u0070" },
  { key = "Tab", mods = "Control", chars = "\u0002\u006e" },
  # ⌃ + [ or ] for navigate to next and previous window
  { key = "[", mods = "Command", chars = "\u0002\u0070" },
  { key = "]", mods = "Command", chars = "\u0002\u006e" },
   # ⌃ + ⇧ + [ or ] for swap to next and previous window
  { key = "{", mods = "Command|Shift", chars = "\u0002\u005b" },
  { key = "}", mods = "Command|Shift", chars = "\u0002\u005d" },
  # ⌃ + 0..9 for navigate to window by number
  { key = "1", mods = "Command", chars = "\u0002\u0031" },
  { key = "2", mods = "Command", chars = "\u0002\u0032" },
  { key = "3", mods = "Command", chars = "\u0002\u0033" },
  { key = "4", mods = "Command", chars = "\u0002\u0034" },
  { key = "5", mods = "Command", chars = "\u0002\u0035" },
  { key = "6", mods = "Command", chars = "\u0002\u0036" },
  { key = "7", mods = "Command", chars = "\u0002\u0037" },
  { key = "8", mods = "Command", chars = "\u0002\u0038" },
  { key = "9", mods = "Command", chars = "\u0002\u0039" },
  # ⌘ + Tab navigate to last window
  # NOTE "$HOME/.config/tmux/tmux.conf"
  # { key = "Tab", mods = "Control", chars = "\u0002\u0009" },
  # clear pane screen and scroll history
  # NOTE "$HOME/.config/tmux/tmux.conf"
  { key = "K", mods = "Command", chars = "\u0002\u004b" },

  # NOTE: nvim
  #
  # ⌥ + d adds a pane to the right (splits window vertically)
  { key = "D",  mods = "Option", chars = "\u0020|" },
  # ⌥ + ⇧ + d adds a pane below (splits window horizontally)
  { key = "D",  mods = "Option|Shift", chars = "\u0020-", mode = "AppCursor" },
  # ⌥ + w to close vim buffer
  { key = "W",  mods = "Option", chars = "\u0020\u0062d", mode = "AppCursor" },
  # emulates ^ + hjkl
  # NOTE "$HOME/.config/nvim/lua/config/keymaps.lua"
  { key = "Down", mods = "Command|Option", chars = "\u000a", mode = "AppCursor" },
  { key = "Up", mods = "Command|Option", chars = "\u000b", mode = "AppCursor" },
  { key = "Left", mods = "Command|Option", chars = "\u0008", mode = "AppCursor" },
  { key = "Right", mods = "Command|Option", chars = "\u000c", mode = "AppCursor" },
  # ^ + arrows are for resizing of the nvim panes
  # NOTE see default nvim bindings
  # NOTE: mission control shorcuts should be turned off
  #
  # ⌥ + Tab + Shift for navigate to next and previous buffer
  { key = "Tab", mods = "Option|Shift", chars = "\u0048", mode = "AppCursor" },
  { key = "Tab", mods = "Option", chars = "\u004c", mode = "AppCursor" },
  # ⌥ + [ or ] for navigate to next and previous buffer
  { key = "[", mods = "Option", chars = "\u0048", mode = "AppCursor" },
  { key = "]", mods = "Option", chars = "\u004c", mode = "AppCursor" },
  # ⌥ + ⇧ + [ or ] for swap buffer to left or right 
  { key = "[", mods = "Option|Shift", chars = "[B", mode = "AppCursor" },
  { key = "]", mods = "Option|Shift", chars = "]B", mode = "AppCursor" },
  # ⌥ + Home or End for navigate to start and end of a line
  { key = "Home", mods = "Option", chars = "0", mode = "AppCursor" },
  { key = "End", mods = "Option", chars = "$", mode = "AppCursor" },
  # ⌥ + ⇧ + arrows for changing pane width and height
  { key = "Down", mods = "Option|Shift", chars = "\u001b[1;5B", mode = "AppCursor" },
  { key = "Up", mods = "Option|Shift", chars = "\u001b[1;5A", mode = "AppCursor" },
  { key = "Left", mods = "Option|Shift", chars = "\u001b[1;5D", mode = "AppCursor" },
  { key = "Right", mods = "Option|Shift", chars = "\u001b[1;5C", mode = "AppCursor" },
 
  # ⌥ + Left or Right for jump backward and forward by words
  # { key = "Left", mods = "Option", chars = "\u001b[1;3D" },
  # { key = "Right", mods = "Option", chars = "\u0077", mode = "AppCursor" },
  # ⌥ + Up or Down for move line
  # { key = "Up", mods = "Option", chars = "\u001bk", mode = "AppCursor" },
  # { key = "Down", mods = "Option", chars = "\u001bj", mode = "AppCursor" },
]
