import = [
  "$HOME/.config/catppuccin/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "source ~/.zshrc; ftmux",
]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_title = true

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
size = 16

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
  # tmux
  # NOTE prefix key is C-a "$HOME/.config/tmux/tmux.conf"
  # https://www.danielcorin.com/til/alacritty/rebuilding-my-iterm-setup-in-alacritty/
  # ⌘ + enter puts window in macOS full screen
  { key = "Enter", mods = "Command", action = "ToggleFullscreen"},
  # opt + right and left jump between words
  # NOTE "$HOME/.config/zsh/bindings.sh"
  # ⌘ + d adds a pane to the right (splits window vertically)
  { key = "D",  mods = "Command", chars = "\u0001%" },
  # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
  { key = "D",  mods = "Command|Shift", chars = "\u0001\"" },
  # ⌘ + w prompts you to close the pane, "y" to confirm
  { key = "W",  mods = "Command", chars = "\u0001x" },
  { key = "T", mods = "Command", chars = "\u0001\u0063" },
  # ⌘ + arrows are for directional navigation around the panes
  { key = "Down", mods = "Command", chars = "\u0001\u001b[B" },
  { key = "Up", mods = "Command", chars = "\u0001\u001b[A" },
  { key = "Left", mods = "Command", chars = "\u0001\u001b[D" },
  { key = "Right", mods = "Command", chars = "\u0001\u001b[C" },
  # ⌘ + ^ + arrows are for directional resizing of the panes
  { key = "Down", mods = "Command|Control", chars = "\u0001\u001b[1;5B" },
  { key = "Up", mods = "Command|Control", chars = "\u0001\u001b[1;5A" },
  { key = "Left", mods = "Command|Control", chars = "\u0001\u001b[1;5D" },
  { key = "Right", mods = "Command|Control", chars = "\u0001\u001b[1;5C" },
  # ⌘ + ⇧ + enter for zoom pane
  { key = "Enter", mods = "Command|Shift", chars = "\u0001\u007a" },
  # ⌃ + Tab + Shift for navigate to next and previous window
  { key = "Tab", mods = "Control|Shift", chars = "\u0001\u0070" },
  { key = "Tab", mods = "Control", chars = "\u0001\u006e" },
  # ⌃ + [] for swap to next and previous window
  { key = "[", mods = "Control", chars = "\u0001\u005b" },
  { key = "]", mods = "Control", chars = "\u0001\u005d" },
  # ⌃ + 0..9 for navigate to window by number
  { key = "1", mods = "Control", chars = "\u0001\u0031" },
  { key = "2", mods = "Control", chars = "\u0001\u0032" },
  { key = "3", mods = "Control", chars = "\u0001\u0033" },
  { key = "4", mods = "Control", chars = "\u0001\u0034" },
  { key = "5", mods = "Control", chars = "\u0001\u0035" },
  { key = "6", mods = "Control", chars = "\u0001\u0036" },
  { key = "7", mods = "Control", chars = "\u0001\u0037" },
  { key = "8", mods = "Control", chars = "\u0001\u0038" },
  { key = "9", mods = "Control", chars = "\u0001\u0039" },
  # ⌘ + Tab navigate to last window
  # NOTE "$HOME/.config/tmux/tmux.conf"
  # { key = "Tab", mods = "Control", chars = "\u0001\u0009" },
  # clear pane screen and scroll history
  # NOTE "$HOME/.config/tmux/tmux.conf"
  { key = "K", mods = "Command", chars = "\u0001\u004b" },

  # nvim
  # ⌥ + d adds a pane to the right (splits window vertically)
  { key = "D",  mods = "Option", chars = "\u0020|" },
  # ⌥ + ⇧ + d adds a pane below (splits window horizontally)
  { key = "D",  mods = "Option|Shift", chars = "\u0020-" },
  # ⌘ + ⌥ + arrows are for directional navigation around the nvim panes
  { key = "W",  mods = "Option", chars = "\u0020\u0062d" },
  # emulates ^ + hjkl
  # NOTE "$HOME/.config/nvim/lua/config/keymaps.lua"
  { key = "Down", mods = "Command|Option", chars = "\u000a" },
  { key = "Up", mods = "Command|Option", chars = "\u000b" },
  { key = "Left", mods = "Command|Option", chars = "\u0008" },
  { key = "Right", mods = "Command|Option", chars = "\u000c" },
  # ^ + arrows are for resizing of the nvim panes
  # NOTE see default nvim bindings
  # ⌥ + Tab + Shift for navigate to next and previous buffer
  { key = "Tab", mods = "Option|Shift", chars = "\u0048" },
  { key = "Tab", mods = "Option", chars = "\u004c" },
]
